DDAC/Models/Booking.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace DDAC.Models
{
    public class Booking
    {
     [Key]
        public int BookingID { get; set; }
    [Required]
        public int ShipID { get; set; }
     [Required]
        public int ContainerID { get; set; }
     [Required]
        public int Price { get; set; }
     [Required]
        public int Date { get; set; }
     [Required]
        public int Time { get; set; }
     [Required]
        public int Departure { get; set; }
     [Required]
        public int Arrival { get; set; }
    }
}

DDAC/Models/Charter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace DDAC.Models
{
    public class Charter
    {
        [Key]
        public int ShipID { get; set; }
        [Required]
        public string ShipName { get; set; }
        [Required]
        public string ShipInfo { get; set; }
        [Required]
        public int ContainersCarried { get; set; }
    }
}

DDAC/Models/Container.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace DDAC.Models
{
    public class Container
    {
        [Key]
        public int ContainerID { get; set; }
        [Required]
        public string ContainerName { get; set; }
        [Required]
        public string ContainerInfo { get; set; }
        [Required]
        public int Amount { get; set; }
        [Required]
        public double Weight { get; set; }
    }
}

DDAC/Models/Maersk_LineContent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace DDAC.Models
{
    public class Maersk_LineContent : DbContext
    {
      
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, please use data migrations.
        // For more information refer to the documentation:
        // http://msdn.microsoft.com/en-us/data/jj591621.aspx
    
        public Maersk_LineContent() : base("name=Maersk_LineContext")
        {
        }

        public System.Data.Entity.DbSet<DDAC.Models.Booking> Bookings { get; set; }

        public System.Data.Entity.DbSet<DDAC.Models.Container> Containers { get; set; }

        //public System.Data.Entity.DbSet<DDAC.Models.Employee> Employees { get; set; }

        public System.Data.Entity.DbSet<DDAC.Models.Charter> Charter { get; set; }

        public System.Data.Entity.DbSet<DDAC.Models.Shipyard> Shipyard { get; set; }

        public System.Data.Entity.DbSet<DDAC.Models.Warehouse> Warehouses { get; set; }
   
}
}

DDAC/Models/Shipyard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;


namespace DDAC.Models
{
    public class Shipyard
    {
        
            [Key]
            public int ShipyardID { get; set; }
            [Required]
            public string YardName { get; set; }
            [Required]
            public int DockedShip { get; set; }
            [Required]
            public int DockNumber { get; set; }
            [Required]
            public int TotalContainers { get; set; }
        

    }
}

DDAC/Models/Warehouse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace DDAC.Models
{
    public class Warehouse
    {
        [Key]
        public int WarehouseNo{ get; set; }
        [Required]
        public string WarehouseName { get; set; }
        [Required]
        public string Manager { get; set; }
        [Required]
        public int ContainerStored { get; set; }
    }
}

DDAC/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DDAC.Models;

namespace Maersk_Line.Controllers
{
    public class BookingsController : Controller
    {
        private Maersk_LineContent db = new Maersk_LineContent();

        // GET: Bookings
        public ActionResult Booking()
        {
            return View(db.Bookings.ToList());
        }
    }
}

DDAC/Controllers/CharterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDAC.Controllers
{
    public class CharterController : Controller
    {
        // GET: Charter
        public ActionResult Charter()
        {
            return View();
        }
    }
}

DDAC/Controllers/ContainerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDAC.Controllers
{
    public class ContainerController : Controller
    {
        // GET: Container
        public ActionResult Container()
        {
            return View();
        }
    }
}

DDAC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDAC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DDAC/Controllers/ShipyardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDAC.Controllers
{
    public class ShipyardController : Controller
    {
        // GET: Shipyard
        public ActionResult Shipyard()
        {
            return View();
        }
    }
}

DDAC/Controllers/WarehouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDAC.Controllers
{
    public class WarehouseController : Controller
    {
        // GET: Warehouse
        public ActionResult Warehouse()
        {
            return View();
        }
    }
}

DDAC/Views/Booking/Booking.cshtml
@model IEnumerable<DDAC.Models.Booking>
    @{
        Layout = "~/Views/Shared/_Layout.cshtml";
    }


    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title></title>
    </head>
    <body>
        <br />
        <br />

        <div class="tab">
            <button class="tablinks" onclick="openCity(event, 'CreateBooking')">Create Booking</button>
            <button class="tablinks" onclick="openCity(event, 'DeleteBooking')">Delete Booking</button>
            <button class="tablinks" onclick="openCity(event, 'BookingDetails')">Booking Details</button>
            <button class="tablinks" onclick="openCity(event, 'EditBooking')">Edit Booking</button>
        </div>

        <div id="CreateBooking" class="tabcontent">
            <h2>Create Booking</h2>
            &nbsp;

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                var item = new DDAC.Models.Booking();
                <div class="form-horizontal">
                    <h4>Booking</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => item.ShipID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => item.ShipID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => item.ShipID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => item.ContainerID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => item.ContainerID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => item.ContainerID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => item.Price, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => item.Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => item.Price, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => item.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => item.Date, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => item.Date, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => item.Time, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => item.Time, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => item.Time, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => item.Departure, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => item.Departure, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => item.Departure, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => item.Arrival, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => item.Arrival, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => item.Arrival, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

        </div>


        <div id="DeleteBooking" class="tabcontent">
            <h2>Delete</h2>

            <h3>Are you sure you want to delete this?</h3>
            <div>
                <h4>Booking</h4>

                <h2>Index</h2>

                <p>
                    @Html.ActionLink("Create New", "Create")
                </p>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ShipID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ContainerID)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Price)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Date)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Time)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Departure)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Arrival)
                        </th>
                        <th></th>
                    </tr>


                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ShipID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ContainerID)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Price)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Time)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Departure)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Arrival)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.BookingID }) |
                                @Html.ActionLink("Details", "Details", new { id = item.BookingID }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.BookingID })
                            </td>
                        </tr>
                    }

                </table>
                <hr />
                
                @*<dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.ShipID)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ShipID)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ContainerID)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.ContainerID)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Price)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Price)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Date)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Date)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Time)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Time)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Departure)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Departure)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Arrival)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Arrival)
                    </dd>

                </dl>*@

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |

                    </div>
                }
            </div>
        </div>

        <div id="DetailsBooking" class="tabcontent">
            <h3>Tokyo</h3>
            <p>Tokyo is the capital of Japan.</p>
        </div>

        <script>
            function openCity(evt, cityName) {
                var i, tabcontent, tablinks;
                tabcontent = document.getElementsByClassName("tabcontent");
                for (i = 0; i < tabcontent.length; i++) {
                    tabcontent[i].style.display = "none";
                }
                tablinks = document.getElementsByClassName("tablinks");
                for (i = 0; i < tablinks.length; i++) {
                    tablinks[i].className = tablinks[i].className.replace(" active", "");
                }
                document.getElementById(cityName).style.display = "block";
                evt.currentTarget.className += " active";
            }
        </script>

    </body>



</html>

DDAC/Views/Charter/Charter.cshtml
@model DDAC.Models.Charter
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    <h2>Ship Chartering</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Ships</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ShipName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ShipName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ShipName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ShipInfo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ShipInfo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ShipInfo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContainersCarried, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContainersCarried, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContainersCarried, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    </div>
</body>
</html>

DDAC/Views/Container/Container.cshtml
@model DDAC.Models.Container
@{
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    <h2>Assign Container</h2>
    @using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Container</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ContainerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContainerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContainerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContainerInfo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContainerInfo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContainerInfo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    
    </div>
</body>
</html>

DDAC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DDAC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DDAC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    Welcome to MAERSK Group of Companies

</div>

<div class="row">
    <div class="col-md-4">
        <h2>About Us</h2>
        <p>
            A.P. Moller - Maersk is an integrated transport & logistics company with multiple brands and is a global leader in container shipping and ports. Including a stand-alone Energy division, the company employs roughly 88,000 employees across operations in 130 countries.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
   </div>

DDAC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MAERSK", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><div class="dropdown">
                    <button class="dropbtn">Manage Shipping</button>
                    <div class="dropdown-content">
                    <p>@Html.ActionLink("Create Booking", "Booking", "Booking")</p>
                    <p>@Html.ActionLink("Assign Containers", "Container", "Container")</p>
                    <p>@Html.ActionLink("Ship Chartering", "Charter", "Charter")</p>
                     </div>
                    </div>
                    </li>
                    <li><div class="dropdown">
                    <button class="dropbtn">Ground Management</button>
                    <div class="dropdown-content">
                    <p>@Html.ActionLink("Register Warehouse", "Warehouse", "Warehouse")</p>
                    <p>@Html.ActionLink("Register Shipyard", "Shipyard", "Shipyard")</p>
                    </div>
                    </div></li>
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year -Narash Kumar TP024196</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DDAC/Views/Shipyard/Shipyard.cshtml
@model DDAC.Models.Shipyard
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    <h2>Register Shipyard</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>ShipYard</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.YardName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.YardName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.YardName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DockedShip, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DockedShip, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DockedShip, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DockNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DockNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DockNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TotalContainers, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TotalContainers, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TotalContainers, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

    
    </div>
</body>
</html>

DDAC/Views/Warehouse/Warehouse.cshtml
@model DDAC.Models.Warehouse
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    <h2>Register Warehouse</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Warehouse</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.WarehouseName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.WarehouseName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.WarehouseName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Manager, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Manager, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Manager, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ContainerStored, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ContainerStored, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ContainerStored, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    
    </div>
</body>
</html>